version: '3'

services:
  api-smartranking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-smartranking
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
